account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('register/',views.register,name='register'),
]

job/urls.py
from django.urls import path
from . import views

app_name = 'job'

urlpatterns = [
    path('',views.job_list,name='job_list'),
    path('<str:slug>/',views.job_detail,name='job_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('account.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('jobs/',include('job.urls',namespace='jobs')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

job/models.py
from typing import Iterable
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField( max_length=150)
    slug = models.SlugField(blank=True,null=True)
    def __str__(self) -> str:
        return self.name
    
    
    def save(self,*args, **kwargs):
        self.slug = slugify(self.name)
        super(Category,self).save(*args, **kwargs)    

        
    
def image_upload(instance,filename:str):

    extension = filename.split('.')[1]
    return f'jobs/{instance.job_name}.{extension}'


JOB_TYPE = (
    ('Part Time','Part Time'),
    ('Full Time','Full Time'),
    ('Remote','Remote'),
)


class Job(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job_name = models.CharField(max_length=150)
    slug = models.SlugField(blank=True,null=True)
    category = models.ForeignKey(Category,  on_delete=models.CASCADE)
    job_type = models.CharField(max_length=50,choices=JOB_TYPE)
    salary = models.IntegerField()
    vacancy = models.IntegerField()
    description = models.TextField()
    location = models.CharField(max_length=150)
    published_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to=image_upload, height_field=None, width_field=None, max_length=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.job_name
    
    def save(self,*args, **kwargs):
        self.slug = slugify(self.job_name)
        super(Job,self).save(*args, **kwargs)  
      
    
def cv_upload(instance,filename:str):
    extension = filename.split('.')[1]
    return f'cv/{instance.name}.{extension}'
class ApplyJob(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    email = models.EmailField( max_length=254)
    linkedin = models.URLField(max_length=400)
    cv = models.FileField( upload_to=None, max_length=100)
    cover_letter = models.TextField()

    class Meta:
        verbose_name =("ApplyJob")
        verbose_name_plural =("ApplyJobs")

    def __str__(self):
        return self.name


        

job/forms.py
from django import forms
from .models import ApplyJob


class ApplyForm(forms.ModelForm):
    class Meta:
        model = ApplyJob
        fields = '__all__'
        exclude = 'job','user'

account/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.http import HttpResponse

# Create your views here.
def login_view(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        if username and password:
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('home')
            
        
            
    return render(request,'accounts/login.html')

def register(request):
    if request.method=='POST':
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        username = email.split('@')[0]
        if password1==password2:
            try:
                is_user = User.objects.get(username=username)
            
                return HttpResponse('This Email Already Have Account')
            except:
                user = User.objects.create_user(username=username,email=email,password=password1)
                login(request,user)
                return redirect('home')
    return render(request,'accounts/register.html')

def logout_view(request):
    logout(request)
    return redirect('accounts:login')

blog/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render

# Create your views here.

job/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.paginator import Paginator
from django.http import HttpResponse
from .models import Job,ApplyJob
from .forms import ApplyForm

# Create your views here.

# FBV CBV MIxins Generics Viewsets ----> 2 lines
def job_list(request):
    jobs = Job.objects.all()
    paginator = Paginator(jobs, 2) #(Queryset,number of objects)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    print(page_obj)
    context = {
        'jobs' : page_obj,
        
    }
    return render(request,'jobs/job_list.html',context)
@login_required(login_url='accounts:login')
def job_detail(request,slug):
    try:
        job = Job.objects.get(slug=slug)
        if request.method=='POST':
            form = ApplyForm(request.POST,request.FILES)
            if form.is_valid():
                my_form = form.save(commit=False)
                my_form.job = job
                my_form.user= request.user
                my_form.save()
                return redirect('home')
        else:
            form = ApplyForm()
         
             
        

    except Job.DoesNotExist:
        print('Error')
        return HttpResponse('No job with this id')  
    context = {
        'job':job,
        'form':form,
    }
    return render(request,'jobs/job_detail.html',context)


# if request.method=='POST':
        #     name = request.POST['name']
        #     email = request.POST['email']
        #     linkedin = request.POST['linkedin']
        #     cv = request.FILES['cv']
        #     cover_letter = request.POST['cover']

        #     apply_job = ApplyJob.objects.create(
        #         job = job,
        #         name = name,
        #         email=email,linkedin=linkedin,
        #         cv=cv,cover_letter=cover_letter,
        #     )


            # apply_job = ApplyJob()
            # apply_job.job=job
            # apply_job.name = name
            # apply_job.email = email
            # apply_job.linkedin = linkedin
            # apply_job.cv = cv
            # apply_job.cover_letter = cover_letter
            # apply_job.save()   

project/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
@login_required(login_url='accounts:login')
def home(request):

    return render(request,'home/home.html')

templates/accounts/login.html
{% extends "base.html" %}
{% block body %}

<title>Login Page</title>
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f2f2f2;
        text-align: center;
    }
    .login-container {
        width: 300px;
        margin: 100px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    input {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
    button {
        width: 100%;
        padding: 10px;
        background-color: #00ff77;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
</style>
</head>
<body>
<div class="login-container">
    <h2>Login</h2>
    <form method="POST">
        {% csrf_token %}
        <input type="text" placeholder="Username" name='username' required>
        <input type="password" placeholder="Password"  name='password' required>
        <button type="submit">Login</button>
    </form>
    <p><a href="#">Forgot password?</a></p>
    <p><a href="{% url "accounts:register" %}">Register</a></p>
</div>
</body>
{% endblock body %}

<!-- <div class="apply_job_form white-bg">
    <h4>Apply for the job</h4>
    <form  method='POST' enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <input type="text" name="" id="">
            <input type="text" name="" id="">
            <input type="text" name="" id="">
            <div class="col-md-12">
                <div class="submit_btn">
                    <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                </div>
            </div>
        </div>
    </form>
</div> -->

templates/accounts/register.html
{% extends "base.html" %}
{% block body %}

<title>Login Page</title>
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f2f2f2;
        text-align: center;
    }
    .login-container {
        width: 300px;
        margin: 100px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    input {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
    button {
        width: 100%;
        padding: 10px;
        background-color: #00ff77;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
</style>
</head>
<body>
<div class="login-container">
    <h2>Sign-up</h2>
    <form method="POST">
        {% csrf_token %}
        <input type="text" placeholder="Email" name='email' required>
        <input type="password" placeholder="Password"  name='password1' required>
        <input type="password" placeholder="Confirm Password"  name='password2' required>
        <button type="submit">Sign-up</button>
    </form>
    <p><a href="{% url "accounts:login" %}">Have an account just login</a></p>
    
</div>
</body>
{% endblock body %}

templates/base.html
<!doctype html>
{% load static %}
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    {% comment %} <link rel="shortcut icon" type="image/x-icon" href="{% static "img/favicon.png" %}"> {% endcomment %}
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="img/logo.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="{% url "home" %}">home</a></li>
                                            <li><a href="{% url "jobs:job_list" %}">Browse Job</a></li>
                                            <li><a href="#">pages <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="candidate.html">Candidates </a></li>
                                                    <li><a href="job_details.html">job details </a></li>
                                                    <li><a href="elements.html">elements</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="#">blog <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="blog.html">blog</a></li>
                                                    <li><a href="single-blog.html">single-blog</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="contact.html">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                    <div class="phone_num d-none d-xl-block">
                                        {% if request.user.is_authenticated %}
                                        <a href="#">{{request.user}}</a>
                                        <a href="{% url "accounts:logout" %}">Logout</a>
                                        {% else %}
                                        <a href="{% url "accounts:login" %}">Login</a>
                                        {% endif %}
                                    </div>
                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="#">Post a Job</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    {% block body %}
    
    {% endblock body %}   


    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="img/logo.png" alt="">
                                </a>
                            </div>
                            <p>
                                finloan@support.com <br>
                                +10 873 672 6782 <br>
                                600/D, Green road, NewYork
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                Company
                            </h3>
                            <ul>
                                <li><a href="#">About </a></li>
                                <li><a href="#"> Pricing</a></li>
                                <li><a href="#">Carrier Tips</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Category
                            </h3>
                            <ul>
                                <li><a href="#">Design & Art</a></li>
                                <li><a href="#">Engineering</a></li>
                                <li><a href="#">Sales & Marketing</a></li>
                                <li><a href="#">Finance</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                            <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                                luckily.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/ajax-form.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/gijgo.min.js' %}"></script>



    <!--contact js-->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>


    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/jobs/job_detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{job}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="job_details_header">
                    <div class="single_jobs white-bg d-flex justify-content-between">
                        <div class="jobs_left d-flex align-items-center">
                            <div class="">
                                <img src="{{job.image.url}}" alt="" style="width:80px;height:80px;">
                            </div>
                            <div class="jobs_conetent">
                                <a href="#"><h4>{{job}}</h4></a>
                                <div class="links_locat d-flex align-items-center">
                                    <div class="location">
                                        <p> <i class="fa fa-map-marker"></i>{{job.location}}</p>
                                    </div>
                                    <div class="location">
                                        <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="jobs_right">
                            <div class="apply_now">
                                <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="descript_wrap white-bg">
                    <div class="single_wrap">
                        <h4>Job description</h4>
                        <p>{{job.description}}</p>
                       
                    </div>
                
                </div>
                <div class="apply_job_form white-bg">
                    <h4>Apply for the job</h4>
                    <form  method='POST' enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            {% bootstrap_form form %}
                            <div class="col-md-12">
                                <div class="submit_btn">
                                    <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>Job Summery</h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>Published on: <span>{{job.published_on|date:"D d M o"}}</span></li>
                            <li>Vacancy: <span>{{job.vacancy}} Position</span></li>
                            <li>Salary: <span>{{job.salary}}k/y</span></li>
                            <li>Location: <span>{{job.location}}</span></li>
                            <li>Job Nature: <span> {{job.job_type}}</span></li>
                        </ul>
                    </div>
                </div>
                <div class="share_wrap d-flex">
                    <span>Share at:</span>
                    <ul>
                        <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                    </ul>
                </div>
                <div class="job_location_wrap">
                    <div class="job_lok_inner">
                        <div id="map" style="height: 200px;"></div>
                        <script>
                          function initMap() {
                            var uluru = {lat: -25.363, lng: 131.044};
                            var grayStyles = [
                              {
                                featureType: "all",
                                stylers: [
                                  { saturation: -90 },
                                  { lightness: 50 }
                                ]
                              },
                              {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                            ];
                            var map = new google.maps.Map(document.getElementById('map'), {
                              center: {lat: -31.197, lng: 150.744},
                              zoom: 9,
                              styles: grayStyles,
                              scrollwheel:  false
                            });
                          }
                          
                        </script>
                        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                        
                      </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}